'use strict';

const { alpha, mix } = require('./palette');

/**
 * Builds a complete VS Code colour theme from a palette variant.
 *
 * Role assignments are shared across every variant so the three themes stay
 * recognisably the same design. Only the palette numbers differ.
 *
 * Token roles:
 *   teal      functions, methods, decorators   (hero — most frequent accent)
 *   sky       properties, tags, attributes
 *   lavender  keywords, control flow, storage, operators-as-words
 *   orchid    built-ins, language constants, CSS units, regex groups
 *   rose      `this`/self, HTML tags, markdown lists   (syntax only — never errors)
 *   apricot   numbers, constants, enum members, escape sequences
 *   amber     types, classes, interfaces, namespaces
 *   green     strings
 *   red       errors, invalid, deletions   (state — red means broken, nothing else)
 *   muted     comments, ghost text
 *   subtle    punctuation, delimiters, brackets
 *   faint     line numbers, active indent guide — quiet but readable
 *   text      plain identifiers and variables
 */
function buildTheme(variant) {
  const { neutrals: n, accents: a, states: st, type } = variant;
  const isDark = type === 'dark';

  // Tint strengths differ by polarity: a 25% wash reads as a clear highlight on
  // a dark base but as mud on a light one, where less alpha carries further.
  const t = isDark
    ? { sel: 0.3, selDim: 0.18, hl: 0.16, find: 0.4, findDim: 0.22, diff: 0.16, gutter: 0.9 }
    : { sel: 0.22, selDim: 0.12, hl: 0.14, find: 0.32, findDim: 0.18, diff: 0.14, gutter: 0.85 };

  // Diff and git states get their own greens/reds: the syntax green is tuned to
  // sit next to a string, not to wash a whole line.
  const added = isDark ? mix(a.green, n.base, 0.15) : a.green;
  const removed = isDark ? mix(st.red, n.base, 0.15) : st.red;
  const shadow = isDark ? alpha('#000000', 0.4) : alpha(n.bright, 0.12);

  const colors = {
    // -- Base ---------------------------------------------------------------
    focusBorder: alpha(a.teal, 0.7),
    foreground: n.text,
    descriptionForeground: n.muted,
    errorForeground: st.red,
    'icon.foreground': n.subtle,
    'widget.border': n.surface1,
    'widget.shadow': shadow,
    'selection.background': alpha(n.tint, t.sel),
    'sash.hoverBorder': a.teal,
    disabledForeground: n.faint,

    'textLink.foreground': a.sky,
    'textLink.activeForeground': a.teal,
    'textBlockQuote.background': n.mantle,
    'textBlockQuote.border': a.teal,
    'textCodeBlock.background': n.mantle,
    'textPreformat.foreground': a.apricot,
    'textPreformat.background': n.surface0,
    'textSeparator.foreground': n.surface1,

    // -- Window / title -----------------------------------------------------
    'titleBar.activeBackground': n.crust,
    'titleBar.activeForeground': n.text,
    'titleBar.inactiveBackground': n.crust,
    'titleBar.inactiveForeground': n.muted,
    'titleBar.border': isDark ? n.crust : n.surface1,

    // -- Buttons ------------------------------------------------------------
    // The hero accent carries the primary action. Foreground is the darkest
    // neutral on dark variants so a saturated fill never fights the label.
    'button.background': a.teal,
    'button.foreground': isDark ? n.crust : n.base,
    'button.hoverBackground': mix(a.teal, isDark ? n.bright : n.bright, 0.15),
    'button.secondaryBackground': n.surface1,
    'button.secondaryForeground': n.text,
    'button.secondaryHoverBackground': n.surface2,
    'button.border': alpha(n.surface2, 0),
    'checkbox.background': n.elevated,
    'checkbox.foreground': a.teal,
    'checkbox.border': n.surface1,

    // -- Dropdowns / inputs -------------------------------------------------
    'dropdown.background': n.elevated,
    'dropdown.listBackground': n.elevated,
    'dropdown.foreground': n.text,
    'dropdown.border': n.surface1,

    'input.background': isDark ? n.crust : n.surface0,
    'input.foreground': n.text,
    'input.border': n.surface1,
    'input.placeholderForeground': n.muted,
    'inputOption.activeBackground': alpha(a.teal, 0.25),
    'inputOption.activeForeground': a.teal,
    'inputOption.activeBorder': alpha(a.teal, 0.5),
    'inputValidation.errorBackground': mix(n.base, st.red, 0.2),
    'inputValidation.errorBorder': st.red,
    'inputValidation.errorForeground': n.text,
    'inputValidation.warningBackground': mix(n.base, a.amber, 0.2),
    'inputValidation.warningBorder': a.amber,
    'inputValidation.warningForeground': n.text,
    'inputValidation.infoBackground': mix(n.base, a.sky, 0.2),
    'inputValidation.infoBorder': a.sky,
    'inputValidation.infoForeground': n.text,

    // -- Scrollbars ---------------------------------------------------------
    'scrollbar.shadow': shadow,
    'scrollbarSlider.background': alpha(n.surface2, 0.4),
    'scrollbarSlider.hoverBackground': alpha(n.surface2, 0.6),
    'scrollbarSlider.activeBackground': alpha(a.teal, 0.5),

    // -- Badges / progress --------------------------------------------------
    'badge.background': a.teal,
    'badge.foreground': isDark ? n.crust : n.base,
    'activityBarBadge.background': a.teal,
    'activityBarBadge.foreground': isDark ? n.crust : n.base,
    'progressBar.background': a.teal,

    // -- Lists / trees ------------------------------------------------------
    'list.activeSelectionBackground': isDark ? n.surface0 : n.surface1,
    'list.activeSelectionForeground': n.bright,
    'list.inactiveSelectionBackground': isDark ? n.elevated : n.surface0,
    'list.inactiveSelectionForeground': n.text,
    'list.hoverBackground': alpha(n.surface1, 0.5),
    'list.hoverForeground': n.text,
    'list.focusBackground': isDark ? n.surface0 : n.surface1,
    'list.focusForeground': n.bright,
    'list.focusOutline': alpha(a.teal, 0),
    'list.highlightForeground': a.teal,
    'list.focusHighlightForeground': a.teal,
    'list.errorForeground': st.red,
    'list.warningForeground': a.amber,
    'list.dropBackground': alpha(a.lavender, 0.2),
    'list.deemphasizedForeground': n.muted,
    'listFilterWidget.background': n.elevated,
    'listFilterWidget.outline': a.teal,
    'listFilterWidget.noMatchesOutline': st.red,
    'tree.indentGuidesStroke': n.surface1,
    'tree.inactiveIndentGuidesStroke': alpha(n.surface1, 0.5),

    // -- Activity bar -------------------------------------------------------
    'activityBar.background': n.crust,
    'activityBar.foreground': a.teal,
    'activityBar.inactiveForeground': n.muted,
    'activityBar.border': isDark ? n.crust : n.surface1,
    'activityBar.activeBorder': a.teal,
    'activityBar.activeBackground': alpha(a.teal, 0.08),
    'activityBarTop.foreground': a.teal,
    'activityBarTop.inactiveForeground': n.muted,
    'activityBarTop.activeBorder': a.teal,

    // -- Side bar -----------------------------------------------------------
    'sideBar.background': n.mantle,
    'sideBar.foreground': n.subtle,
    'sideBar.border': isDark ? n.mantle : n.surface1,
    'sideBarTitle.foreground': n.muted,
    'sideBarTitle.background': n.mantle,
    'sideBarSectionHeader.background': n.mantle,
    'sideBarSectionHeader.foreground': n.text,
    'sideBarSectionHeader.border': alpha(n.surface1, 0.6),
    'sideBarStickyScroll.background': n.mantle,

    // -- Editor groups & tabs ----------------------------------------------
    'editorGroup.border': isDark ? n.crust : n.surface1,
    'editorGroup.dropBackground': alpha(a.lavender, 0.2),
    'editorGroupHeader.tabsBackground': n.crust,
    'editorGroupHeader.tabsBorder': isDark ? n.crust : n.surface1,
    'editorGroupHeader.noTabsBackground': n.crust,
    'editorGroupHeader.border': alpha(n.surface1, 0),

    // The active tab is marked by a teal top border plus the editor background
    // bleeding upward, so the tab reads as continuous with the buffer below it.
    'tab.activeBackground': n.base,
    'tab.activeForeground': n.bright,
    'tab.activeBorderTop': a.teal,
    'tab.activeBorder': alpha(n.base, 0),
    'tab.inactiveBackground': n.crust,
    'tab.inactiveForeground': n.muted,
    'tab.unfocusedActiveBackground': n.base,
    'tab.unfocusedActiveForeground': n.subtle,
    'tab.unfocusedActiveBorderTop': alpha(a.teal, 0.4),
    'tab.unfocusedInactiveForeground': n.muted,
    'tab.border': isDark ? n.crust : n.surface1,
    'tab.hoverBackground': n.elevated,
    'tab.hoverForeground': n.text,
    'tab.activeModifiedBorder': a.amber,
    'tab.inactiveModifiedBorder': alpha(a.amber, 0.5),
    'tab.lastPinnedBorder': n.surface1,
    'editorPane.background': n.base,

    // -- Editor -------------------------------------------------------------
    'editor.background': n.base,
    'editor.foreground': n.text,
    'editorLineNumber.foreground': n.faint,
    'editorLineNumber.activeForeground': a.teal,
    'editorLineNumber.dimmedForeground': alpha(n.surface2, 0.6),
    'editorCursor.foreground': a.teal,
    'editorCursor.background': n.base,
    'editorMultiCursor.primary.foreground': a.teal,
    'editorMultiCursor.secondary.foreground': a.lavender,

    // The selection wash is a desaturated tint no syntax role owns, and there
    // is no selectionForeground: token colours must survive being selected.
    'editor.selectionBackground': alpha(n.tint, t.sel),
    'editor.inactiveSelectionBackground': alpha(n.tint, t.selDim),
    'editor.selectionHighlightBackground': alpha(a.teal, t.hl),
    'editor.selectionHighlightBorder': alpha(a.teal, 0),
    'editor.wordHighlightBackground': alpha(a.sky, t.hl),
    'editor.wordHighlightStrongBackground': alpha(a.teal, t.hl + 0.06),
    'editor.wordHighlightTextBackground': alpha(a.sky, t.hl),

    'editor.findMatchBackground': alpha(a.apricot, t.find),
    'editor.findMatchBorder': alpha(a.apricot, 0.8),
    'editor.findMatchHighlightBackground': alpha(a.amber, t.findDim),
    'editor.findMatchHighlightBorder': alpha(a.amber, 0),
    'editor.findRangeHighlightBackground': alpha(n.surface1, 0.5),
    'editor.currentSearchMatchHighlightBackground': alpha(a.apricot, t.find),

    'editor.hoverHighlightBackground': alpha(a.sky, 0.12),
    'editor.lineHighlightBackground': isDark ? n.surface0 : alpha(n.surface0, 0.7),
    'editor.lineHighlightBorder': alpha(n.surface0, 0),
    'editor.rangeHighlightBackground': alpha(n.surface1, 0.4),
    'editor.symbolHighlightBackground': alpha(a.teal, 0.2),
    'editorLink.activeForeground': a.teal,
    'editorWhitespace.foreground': alpha(n.surface2, 0.5),
    'editorIndentGuide.background1': n.surface1,
    'editorIndentGuide.activeBackground1': n.faint,
    'editorInlayHint.background': alpha(n.surface1, 0.5),
    'editorInlayHint.foreground': n.muted,
    'editorInlayHint.typeBackground': alpha(n.surface1, 0.5),
    'editorInlayHint.typeForeground': n.muted,
    'editorInlayHint.parameterBackground': alpha(n.surface1, 0.5),
    'editorInlayHint.parameterForeground': n.muted,
    'editorRuler.foreground': alpha(n.surface1, 0.8),
    'editorCodeLens.foreground': n.muted,
    'editorLightBulb.foreground': a.amber,
    'editorLightBulbAutoFix.foreground': a.teal,
    'editorBracketMatch.background': alpha(a.teal, 0.18),
    'editorBracketMatch.border': alpha(a.teal, 0.6),
    'editorUnicodeHighlight.border': a.amber,
    'editorUnicodeHighlight.background': alpha(a.amber, 0.12),

    // Six-step bracket ladder. Ordered to alternate warm and cool so adjacent
    // depths never sit next to each other on the wheel. Each step is pulled
    // 30% toward text: brackets are structure hints, not tokens, and should
    // never compete with the code between them.
    'editorBracketHighlight.foreground1': mix(a.teal, n.text, 0.3),
    'editorBracketHighlight.foreground2': mix(a.lavender, n.text, 0.3),
    'editorBracketHighlight.foreground3': mix(a.amber, n.text, 0.3),
    'editorBracketHighlight.foreground4': mix(a.sky, n.text, 0.3),
    'editorBracketHighlight.foreground5': mix(a.orchid, n.text, 0.3),
    'editorBracketHighlight.foreground6': mix(a.green, n.text, 0.3),
    'editorBracketHighlight.unexpectedBracket.foreground': st.red,

    'editorError.foreground': st.red,
    'editorError.background': alpha(st.red, 0),
    'editorWarning.foreground': a.amber,
    'editorWarning.background': alpha(a.amber, 0),
    'editorInfo.foreground': a.sky,
    'editorInfo.background': alpha(a.sky, 0),
    'editorHint.foreground': a.teal,
    'problemsErrorIcon.foreground': st.red,
    'problemsWarningIcon.foreground': a.amber,
    'problemsInfoIcon.foreground': a.sky,

    'editorGutter.background': n.base,
    'editorGutter.modifiedBackground': alpha(a.sky, t.gutter),
    'editorGutter.addedBackground': alpha(added, t.gutter),
    'editorGutter.deletedBackground': alpha(removed, t.gutter),
    'editorGutter.foldingControlForeground': n.subtle,
    'editorGutter.commentRangeForeground': n.surface2,

    'editorOverviewRuler.background': n.base,
    'editorOverviewRuler.border': alpha(n.crust, 0),
    'editorOverviewRuler.findMatchForeground': alpha(a.apricot, 0.6),
    'editorOverviewRuler.rangeHighlightForeground': alpha(n.surface2, 0.6),
    'editorOverviewRuler.selectionHighlightForeground': alpha(a.teal, 0.4),
    'editorOverviewRuler.wordHighlightForeground': alpha(a.sky, 0.4),
    'editorOverviewRuler.wordHighlightStrongForeground': alpha(a.teal, 0.5),
    'editorOverviewRuler.modifiedForeground': alpha(a.sky, 0.6),
    'editorOverviewRuler.addedForeground': alpha(added, 0.6),
    'editorOverviewRuler.deletedForeground': alpha(removed, 0.6),
    'editorOverviewRuler.errorForeground': st.red,
    'editorOverviewRuler.warningForeground': a.amber,
    'editorOverviewRuler.infoForeground': a.sky,
    'editorOverviewRuler.bracketMatchForeground': alpha(a.teal, 0.5),

    // -- Widgets ------------------------------------------------------------
    'editorWidget.background': n.elevated,
    'editorWidget.foreground': n.text,
    'editorWidget.border': n.surface1,
    'editorWidget.resizeBorder': a.teal,
    'editorHoverWidget.background': n.elevated,
    'editorHoverWidget.foreground': n.text,
    'editorHoverWidget.border': n.surface1,
    'editorHoverWidget.highlightForeground': a.teal,
    'editorSuggestWidget.background': n.elevated,
    'editorSuggestWidget.foreground': n.text,
    'editorSuggestWidget.border': n.surface1,
    'editorSuggestWidget.selectedBackground': n.surface1,
    'editorSuggestWidget.selectedForeground': n.bright,
    'editorSuggestWidget.selectedIconForeground': a.teal,
    'editorSuggestWidget.highlightForeground': a.teal,
    'editorSuggestWidget.focusHighlightForeground': a.teal,
    'editorSuggestWidgetStatus.foreground': n.muted,
    // Ghost text is read, not glanced at: it gets comment-level contrast.
    'editorGhostText.foreground': n.muted,
    'editorStickyScroll.background': n.mantle,
    'editorStickyScrollHover.background': n.surface0,
    'editorMarkerNavigation.background': n.elevated,
    'editorMarkerNavigationError.background': st.red,
    'editorMarkerNavigationWarning.background': a.amber,
    'editorMarkerNavigationInfo.background': a.sky,

    'peekView.border': a.teal,
    'peekViewEditor.background': isDark ? n.crust : n.surface0,
    'peekViewEditor.matchHighlightBackground': alpha(a.apricot, t.find),
    'peekViewEditor.matchHighlightBorder': alpha(a.apricot, 0),
    'peekViewEditorGutter.background': isDark ? n.crust : n.surface0,
    'peekViewResult.background': n.mantle,
    'peekViewResult.fileForeground': n.bright,
    'peekViewResult.lineForeground': n.muted,
    'peekViewResult.matchHighlightBackground': alpha(a.apricot, t.findDim),
    'peekViewResult.selectionBackground': n.surface0,
    'peekViewResult.selectionForeground': n.bright,
    'peekViewTitle.background': n.elevated,
    'peekViewTitleLabel.foreground': n.bright,
    'peekViewTitleDescription.foreground': n.muted,

    // -- Diff ---------------------------------------------------------------
    'diffEditor.insertedTextBackground': alpha(added, t.diff),
    'diffEditor.insertedLineBackground': alpha(added, t.diff * 0.6),
    'diffEditor.removedTextBackground': alpha(removed, t.diff),
    'diffEditor.removedLineBackground': alpha(removed, t.diff * 0.6),
    'diffEditor.diagonalFill': alpha(n.surface1, 0.6),
    'diffEditor.border': n.surface1,
    'diffEditorGutter.insertedLineBackground': alpha(added, t.diff * 0.5),
    'diffEditorGutter.removedLineBackground': alpha(removed, t.diff * 0.5),
    'diffEditorOverview.insertedForeground': alpha(added, 0.6),
    'diffEditorOverview.removedForeground': alpha(removed, 0.6),
    'diffEditor.unchangedRegionBackground': n.mantle,
    'diffEditor.unchangedCodeBackground': alpha(n.surface0, 0.4),

    'merge.currentHeaderBackground': alpha(a.teal, 0.3),
    'merge.currentContentBackground': alpha(a.teal, 0.12),
    'merge.incomingHeaderBackground': alpha(a.sky, 0.3),
    'merge.incomingContentBackground': alpha(a.sky, 0.12),
    'merge.commonHeaderBackground': alpha(n.surface2, 0.3),
    'merge.commonContentBackground': alpha(n.surface2, 0.12),
    'merge.border': alpha(n.surface1, 0),
    'mergeEditor.change.background': alpha(added, t.diff),
    'mergeEditor.change.word.background': alpha(added, t.diff + 0.1),
    'mergeEditor.conflict.unhandledUnfocused.border': alpha(a.amber, 0.5),
    'mergeEditor.conflict.unhandledFocused.border': a.amber,
    'mergeEditor.conflict.handledUnfocused.border': alpha(a.green, 0.4),
    'mergeEditor.conflict.handledFocused.border': alpha(a.green, 0.8),

    // -- Panel / terminal ---------------------------------------------------
    'panel.background': n.mantle,
    'panel.border': isDark ? n.crust : n.surface1,
    'panel.dropBorder': a.teal,
    'panelTitle.activeBorder': a.teal,
    'panelTitle.activeForeground': n.bright,
    'panelTitle.inactiveForeground': n.muted,
    'panelSection.border': isDark ? n.crust : n.surface1,
    'panelSectionHeader.background': n.mantle,
    'panelSectionHeader.foreground': n.text,
    'panelInput.border': n.surface1,

    'terminal.background': n.mantle,
    'terminal.foreground': n.text,
    'terminal.ansiBlack': isDark ? n.surface1 : n.surface2,
    'terminal.ansiRed': st.red,
    'terminal.ansiGreen': a.green,
    'terminal.ansiYellow': a.amber,
    'terminal.ansiBlue': a.sky,
    'terminal.ansiMagenta': a.lavender,
    'terminal.ansiCyan': a.teal,
    'terminal.ansiWhite': n.text,
    'terminal.ansiBrightBlack': n.surface2,
    'terminal.ansiBrightRed': mix(st.red, n.bright, 0.2),
    'terminal.ansiBrightGreen': mix(a.green, n.bright, 0.2),
    'terminal.ansiBrightYellow': mix(a.amber, n.bright, 0.2),
    'terminal.ansiBrightBlue': mix(a.sky, n.bright, 0.2),
    'terminal.ansiBrightMagenta': mix(a.orchid, n.bright, 0.1),
    'terminal.ansiBrightCyan': mix(a.teal, n.bright, 0.2),
    'terminal.ansiBrightWhite': n.bright,
    'terminal.selectionBackground': alpha(n.tint, t.sel),
    'terminal.inactiveSelectionBackground': alpha(n.tint, t.selDim),
    'terminal.findMatchBackground': alpha(a.apricot, t.find),
    'terminal.findMatchHighlightBackground': alpha(a.amber, t.findDim),
    'terminal.border': n.surface1,
    'terminal.tab.activeBorder': a.teal,
    'terminalCursor.foreground': a.teal,
    'terminalCursor.background': n.mantle,
    'terminalCommandDecoration.defaultBackground': n.surface2,
    'terminalCommandDecoration.successBackground': a.green,
    'terminalCommandDecoration.errorBackground': st.red,

    // -- Status bar ---------------------------------------------------------
    'statusBar.background': n.crust,
    'statusBar.foreground': n.subtle,
    'statusBar.border': isDark ? n.crust : n.surface1,
    'statusBar.noFolderBackground': n.crust,
    'statusBar.noFolderForeground': n.muted,
    'statusBar.debuggingBackground': a.apricot,
    'statusBar.debuggingForeground': isDark ? n.crust : n.base,
    'statusBar.debuggingBorder': alpha(a.apricot, 0),
    'statusBarItem.hoverBackground': alpha(n.surface1, 0.6),
    'statusBarItem.activeBackground': alpha(n.surface2, 0.5),
    'statusBarItem.prominentBackground': n.surface1,
    'statusBarItem.prominentForeground': n.bright,
    'statusBarItem.prominentHoverBackground': n.surface2,
    'statusBarItem.remoteBackground': a.teal,
    'statusBarItem.remoteForeground': isDark ? n.crust : n.base,
    'statusBarItem.errorBackground': alpha(st.red, 0),
    'statusBarItem.errorForeground': st.red,
    'statusBarItem.warningBackground': alpha(a.amber, 0),
    'statusBarItem.warningForeground': a.amber,
    'statusBarItem.focusBorder': a.teal,
    'statusBarItem.compactHoverBackground': n.surface2,

    // -- Command palette / quick input --------------------------------------
    'quickInput.background': n.elevated,
    'quickInput.foreground': n.text,
    'quickInputList.focusBackground': n.surface1,
    'quickInputList.focusForeground': n.bright,
    'quickInputList.focusIconForeground': a.teal,
    'quickInputTitle.background': n.surface0,
    'pickerGroup.border': alpha(n.surface1, 0.8),
    'pickerGroup.foreground': a.teal,
    'keybindingLabel.background': alpha(n.surface1, 0.6),
    'keybindingLabel.foreground': n.text,
    'keybindingLabel.border': alpha(n.surface2, 0.4),
    'keybindingLabel.bottomBorder': alpha(n.surface2, 0.6),
    'keybindingTable.headerBackground': n.surface0,
    'keybindingTable.rowsBackground': n.mantle,
    'commandCenter.background': isDark ? n.mantle : n.surface0,
    'commandCenter.foreground': n.subtle,
    'commandCenter.border': n.surface1,
    'commandCenter.activeBackground': n.elevated,
    'commandCenter.activeForeground': n.text,
    'commandCenter.activeBorder': alpha(a.teal, 0.5),
    'commandCenter.inactiveForeground': n.muted,
    'commandCenter.inactiveBorder': alpha(n.surface1, 0.6),

    // -- Notifications / banner ---------------------------------------------
    'notificationCenter.border': n.surface1,
    'notificationCenterHeader.background': n.surface0,
    'notificationCenterHeader.foreground': n.text,
    'notifications.background': n.elevated,
    'notifications.foreground': n.text,
    'notifications.border': n.surface1,
    'notificationToast.border': n.surface1,
    'notificationLink.foreground': a.sky,
    'notificationsErrorIcon.foreground': st.red,
    'notificationsWarningIcon.foreground': a.amber,
    'notificationsInfoIcon.foreground': a.sky,
    'banner.background': n.surface0,
    'banner.foreground': n.text,
    'banner.iconForeground': a.teal,

    // -- Git / SCM ----------------------------------------------------------
    'gitDecoration.addedResourceForeground': a.green,
    'gitDecoration.modifiedResourceForeground': a.amber,
    'gitDecoration.deletedResourceForeground': st.red,
    'gitDecoration.renamedResourceForeground': a.teal,
    'gitDecoration.stageModifiedResourceForeground': a.teal,
    'gitDecoration.stageDeletedResourceForeground': st.red,
    'gitDecoration.untrackedResourceForeground': a.sky,
    'gitDecoration.ignoredResourceForeground': n.faint,
    'gitDecoration.conflictingResourceForeground': a.orchid,
    'gitDecoration.submoduleResourceForeground': a.lavender,
    'scmGraph.historyItemHoverLabelForeground': n.crust,
    'scmGraph.foreground1': a.teal,
    'scmGraph.foreground2': a.lavender,
    'scmGraph.foreground3': a.amber,
    'scmGraph.foreground4': a.sky,
    'scmGraph.foreground5': a.orchid,

    // -- Debug --------------------------------------------------------------
    'debugToolBar.background': n.elevated,
    'debugToolBar.border': n.surface1,
    'debugIcon.breakpointForeground': st.red,
    'debugIcon.breakpointDisabledForeground': alpha(st.red, 0.5),
    'debugIcon.breakpointUnverifiedForeground': n.surface2,
    'debugIcon.breakpointCurrentStackframeForeground': a.amber,
    'debugIcon.breakpointStackframeForeground': a.teal,
    'debugIcon.startForeground': a.green,
    'debugIcon.pauseForeground': a.sky,
    'debugIcon.stopForeground': st.red,
    'debugIcon.disconnectForeground': st.red,
    'debugIcon.restartForeground': a.teal,
    'debugIcon.stepOverForeground': a.lavender,
    'debugIcon.stepIntoForeground': a.lavender,
    'debugIcon.stepOutForeground': a.lavender,
    'debugIcon.continueForeground': a.lavender,
    'debugIcon.stepBackForeground': a.lavender,
    'debugConsole.infoForeground': a.sky,
    'debugConsole.warningForeground': a.amber,
    'debugConsole.errorForeground': st.red,
    'debugConsole.sourceForeground': n.muted,
    'debugConsoleInputIcon.foreground': a.teal,
    'debugTokenExpression.name': a.sky,
    'debugTokenExpression.value': n.subtle,
    'debugTokenExpression.string': a.green,
    'debugTokenExpression.boolean': a.orchid,
    'debugTokenExpression.number': a.apricot,
    'debugTokenExpression.error': st.red,
    'editor.stackFrameHighlightBackground': alpha(a.amber, 0.2),
    'editor.focusedStackFrameHighlightBackground': alpha(a.green, 0.2),

    // -- Testing ------------------------------------------------------------
    'testing.iconPassed': a.green,
    'testing.iconFailed': st.red,
    'testing.iconErrored': st.red,
    'testing.iconQueued': a.amber,
    'testing.iconSkipped': n.surface2,
    'testing.iconUnset': n.surface2,
    'testing.runAction': a.green,
    'testing.message.error.decorationForeground': st.red,
    'testing.message.info.decorationForeground': n.muted,

    // -- Charts / misc ------------------------------------------------------
    'charts.foreground': n.text,
    'charts.lines': n.surface2,
    'charts.red': st.red,
    'charts.blue': a.sky,
    'charts.yellow': a.amber,
    'charts.orange': a.apricot,
    'charts.green': a.green,
    'charts.purple': a.lavender,

    'breadcrumb.foreground': n.muted,
    'breadcrumb.focusForeground': n.text,
    'breadcrumb.activeSelectionForeground': a.teal,
    'breadcrumb.background': n.base,
    'breadcrumbPicker.background': n.elevated,

    'menu.background': n.elevated,
    'menu.foreground': n.text,
    'menu.border': n.surface1,
    'menu.selectionBackground': n.surface1,
    'menu.selectionForeground': n.bright,
    'menu.selectionBorder': alpha(a.teal, 0),
    'menu.separatorBackground': n.surface1,
    'menubar.selectionBackground': n.surface0,
    'menubar.selectionForeground': n.text,
    'menubar.selectionBorder': alpha(a.teal, 0),

    'settings.headerForeground': n.bright,
    'settings.modifiedItemIndicator': a.teal,
    'settings.dropdownBackground': n.elevated,
    'settings.dropdownForeground': n.text,
    'settings.dropdownBorder': n.surface1,
    'settings.dropdownListBorder': n.surface1,
    'settings.checkboxBackground': n.elevated,
    'settings.checkboxForeground': a.teal,
    'settings.checkboxBorder': n.surface1,
    'settings.textInputBackground': isDark ? n.crust : n.surface0,
    'settings.textInputForeground': n.text,
    'settings.textInputBorder': n.surface1,
    'settings.numberInputBackground': isDark ? n.crust : n.surface0,
    'settings.numberInputForeground': a.apricot,
    'settings.numberInputBorder': n.surface1,
    'settings.focusedRowBackground': alpha(n.surface0, 0.6),
    'settings.focusedRowBorder': alpha(a.teal, 0.3),
    'settings.headerBorder': n.surface1,
    'settings.sashBorder': n.surface1,

    'welcomePage.background': n.base,
    'welcomePage.tileBackground': n.mantle,
    'welcomePage.tileHoverBackground': n.surface0,
    'welcomePage.tileBorder': n.surface1,
    'welcomePage.progress.background': n.surface1,
    'welcomePage.progress.foreground': a.teal,
    'walkThrough.embeddedEditorBackground': n.crust,

    'extensionButton.prominentBackground': a.teal,
    'extensionButton.prominentForeground': isDark ? n.crust : n.base,
    'extensionButton.prominentHoverBackground': mix(a.teal, n.bright, 0.15),
    'extensionButton.background': a.teal,
    'extensionButton.foreground': isDark ? n.crust : n.base,
    'extensionButton.hoverBackground': mix(a.teal, n.bright, 0.15),
    'extensionBadge.remoteBackground': a.teal,
    'extensionBadge.remoteForeground': isDark ? n.crust : n.base,
    'extensionIcon.starForeground': a.amber,
    'extensionIcon.verifiedForeground': a.teal,
    'extensionIcon.preReleaseForeground': a.orchid,
    'extensionIcon.sponsorForeground': a.rose,

    'notebook.editorBackground': n.base,
    'notebook.cellEditorBackground': isDark ? n.mantle : n.base,
    'notebook.cellBorderColor': n.surface1,
    'notebook.cellHoverBackground': alpha(n.surface0, 0.4),
    'notebook.focusedCellBackground': alpha(n.surface0, 0.5),
    'notebook.focusedCellBorder': alpha(a.teal, 0.6),
    'notebook.focusedEditorBorder': alpha(a.teal, 0.6),
    'notebook.inactiveFocusedCellBorder': n.surface1,
    'notebook.selectedCellBackground': alpha(n.surface0, 0.5),
    'notebook.selectedCellBorder': n.surface1,
    'notebook.outputContainerBackgroundColor': alpha(n.mantle, 0.5),
    'notebookStatusSuccessIcon.foreground': a.green,
    'notebookStatusErrorIcon.foreground': st.red,
    'notebookStatusRunningIcon.foreground': a.sky,

    'searchEditor.findMatchBackground': alpha(a.apricot, t.findDim),
    'search.resultsInfoForeground': n.muted,
    'symbolIcon.arrayForeground': a.apricot,
    'symbolIcon.booleanForeground': a.orchid,
    'symbolIcon.classForeground': a.amber,
    'symbolIcon.colorForeground': a.orchid,
    'symbolIcon.constantForeground': a.apricot,
    'symbolIcon.constructorForeground': a.teal,
    'symbolIcon.enumeratorForeground': a.amber,
    'symbolIcon.enumeratorMemberForeground': a.apricot,
    'symbolIcon.eventForeground': a.orchid,
    'symbolIcon.fieldForeground': a.sky,
    'symbolIcon.fileForeground': n.text,
    'symbolIcon.folderForeground': n.text,
    'symbolIcon.functionForeground': a.teal,
    'symbolIcon.interfaceForeground': a.amber,
    'symbolIcon.keyForeground': a.sky,
    'symbolIcon.keywordForeground': a.lavender,
    'symbolIcon.methodForeground': a.teal,
    'symbolIcon.moduleForeground': a.amber,
    'symbolIcon.namespaceForeground': a.amber,
    'symbolIcon.nullForeground': a.orchid,
    'symbolIcon.numberForeground': a.apricot,
    'symbolIcon.objectForeground': a.amber,
    'symbolIcon.operatorForeground': a.lavender,
    'symbolIcon.packageForeground': a.amber,
    'symbolIcon.propertyForeground': a.sky,
    'symbolIcon.referenceForeground': a.sky,
    'symbolIcon.snippetForeground': a.green,
    'symbolIcon.stringForeground': a.green,
    'symbolIcon.structForeground': a.amber,
    'symbolIcon.textForeground': n.text,
    'symbolIcon.typeParameterForeground': a.amber,
    'symbolIcon.unitForeground': a.orchid,
    'symbolIcon.variableForeground': n.text,
  };

  // Semantic tokens drive the language servers (TS, Rust, Python via Pylance).
  // They take precedence over TextMate scopes, so the two lists must agree.
  const semanticTokenColors = {
    namespace: a.amber,
    class: a.amber,
    'class.defaultLibrary': a.amber,
    enum: a.amber,
    interface: a.amber,
    struct: a.amber,
    type: a.amber,
    'type.defaultLibrary': a.amber,
    typeParameter: a.amber,
    parameter: { foreground: n.subtle, italic: true },
    variable: n.text,
    'variable.readonly': n.text,
    'variable.readonly.defaultLibrary': a.orchid,
    'variable.defaultLibrary': a.orchid,
    property: a.sky,
    'property.readonly': a.sky,
    'property.declaration': a.sky,
    enumMember: a.apricot,
    decorator: { foreground: a.teal, italic: true },
    event: a.orchid,
    function: a.teal,
    'function.defaultLibrary': a.teal,
    'function.declaration': a.teal,
    method: a.teal,
    'method.declaration': a.teal,
    macro: a.orchid,
    label: a.orchid,
    comment: { foreground: n.muted, italic: true },
    string: a.green,
    keyword: a.lavender,
    number: a.apricot,
    regexp: a.orchid,
    operator: n.subtle,
    selfKeyword: a.rose,
    builtinConstant: a.orchid,
    magicFunction: a.teal,
    module: a.amber,
    'variable.constant': a.apricot,
    newOperator: a.lavender,
    stringLiteral: a.green,
    customLiteral: a.teal,
    numberLiteral: a.apricot,
  };

  const tokenColors = [
    {
      name: 'Comments',
      scope: ['comment', 'punctuation.definition.comment', 'string.comment'],
      settings: { foreground: n.muted, fontStyle: 'italic' },
    },
    {
      name: 'Comment doc keywords',
      scope: [
        'comment.block.documentation storage.type.class',
        'keyword.other.phpdoc',
        'storage.type.annotation.java',
      ],
      settings: { foreground: n.subtle, fontStyle: 'italic' },
    },
    {
      name: 'Plain text and variables',
      scope: [
        'source',
        'variable',
        'variable.other',
        'variable.other.readwrite',
        'meta.definition.variable.name',
        'support.variable',
        'entity.name.variable',
      ],
      settings: { foreground: n.text },
    },
    {
      name: 'Parameters',
      scope: [
        'variable.parameter',
        'meta.function.parameters variable',
        'entity.name.variable.parameter',
        'variable.other.jsdoc',
      ],
      settings: { foreground: n.subtle, fontStyle: 'italic' },
    },
    {
      name: 'Language variables — this, self, super',
      scope: [
        'variable.language',
        'variable.language.this',
        'variable.language.super',
        'variable.language.special.self',
        'keyword.other.this',
      ],
      settings: { foreground: a.rose },
    },
    {
      name: 'Constants and enum members',
      scope: [
        'variable.other.constant',
        'variable.other.enummember',
        'constant.other.caps',
        'constant.other.placeholder',
        'entity.name.constant',
      ],
      settings: { foreground: a.apricot },
    },
    {
      name: 'Numbers',
      scope: [
        'constant.numeric',
        'constant.numeric.integer',
        'constant.numeric.float',
        'keyword.other.unit',
        'meta.preprocessor.numeric',
      ],
      settings: { foreground: a.apricot },
    },
    {
      name: 'Language constants — true, false, null, undefined',
      scope: [
        'constant.language',
        'constant.language.boolean',
        'constant.language.null',
        'constant.language.undefined',
        'constant.language.infinity',
        'constant.language.nan',
        'support.constant',
      ],
      settings: { foreground: a.orchid },
    },
    {
      name: 'Strings',
      scope: [
        'string',
        'string.quoted',
        'string.template',
        'string.other.link',
        'meta.attribute-selector string',
      ],
      settings: { foreground: a.green },
    },
    {
      name: 'String punctuation',
      scope: ['punctuation.definition.string'],
      settings: { foreground: mix(a.green, n.muted, 0.4) },
    },
    {
      name: 'Escapes and template placeholders',
      scope: [
        'constant.character.escape',
        'constant.other.character-class.escape',
        'punctuation.definition.template-expression',
        'punctuation.section.embedded',
        'meta.embedded',
      ],
      settings: { foreground: a.apricot },
    },
    {
      name: 'Regular expressions',
      scope: [
        'string.regexp',
        'constant.other.character-class.set.regexp',
        'constant.character.escape.backslash.regexp',
        'keyword.control.anchor.regexp',
        'keyword.operator.quantifier.regexp',
        'punctuation.definition.group.regexp',
      ],
      settings: { foreground: a.orchid },
    },
    {
      name: 'Keywords and storage',
      scope: [
        'keyword',
        'keyword.control',
        'keyword.other',
        'keyword.operator.new',
        'keyword.operator.expression',
        'keyword.operator.delete',
        'keyword.operator.logical',
        'keyword.operator.instanceof',
        'keyword.operator.in',
        'keyword.operator.of',
        'storage',
        'storage.type',
        'storage.modifier',
        'keyword.declaration',
      ],
      settings: { foreground: a.lavender },
    },
    {
      name: 'Control flow — return, if, await',
      scope: [
        'keyword.control.flow',
        'keyword.control.return',
        'keyword.control.trycatch',
        'keyword.control.conditional',
        'keyword.control.loop',
      ],
      settings: { foreground: a.lavender },
    },
    {
      name: 'Import and export',
      scope: [
        'keyword.control.import',
        'keyword.control.export',
        'keyword.control.from',
        'keyword.control.default',
        'keyword.control.as',
      ],
      settings: { foreground: a.orchid },
    },
    {
      name: 'Operators',
      scope: [
        'keyword.operator',
        'keyword.operator.assignment',
        'keyword.operator.arithmetic',
        'keyword.operator.comparison',
        'keyword.operator.relational',
        'keyword.operator.bitwise',
        'keyword.operator.ternary',
        'keyword.operator.spread',
        'keyword.operator.type.annotation',
      ],
      settings: { foreground: n.subtle },
    },
    {
      name: 'Arrow functions and fat arrows',
      scope: ['storage.type.function.arrow', 'meta.arrow storage.type.function'],
      settings: { foreground: a.lavender },
    },
    {
      name: 'Punctuation and delimiters',
      scope: [
        'punctuation',
        'punctuation.separator',
        'punctuation.terminator',
        'punctuation.accessor',
        'punctuation.definition.parameters',
        'meta.brace',
      ],
      settings: { foreground: n.subtle },
    },
    {
      name: 'Functions and methods',
      scope: [
        'entity.name.function',
        'meta.function-call entity.name.function',
        'support.function',
        'meta.function-call.generic',
        'variable.function',
        'entity.name.method',
        'meta.method-call entity.name.function',
      ],
      settings: { foreground: a.teal },
    },
    {
      name: 'Built-in functions and library support',
      scope: [
        'support.function.builtin',
        'support.function.magic',
        'support.macro',
        'entity.name.function.macro',
      ],
      settings: { foreground: a.teal },
    },
    {
      name: 'Decorators and annotations',
      scope: [
        'meta.decorator',
        'meta.decorator entity.name.function',
        'meta.decorator punctuation.decorator',
        'entity.name.function.decorator',
        'punctuation.definition.annotation',
      ],
      settings: { foreground: a.teal, fontStyle: 'italic' },
    },
    {
      name: 'Types, classes, interfaces, namespaces',
      scope: [
        'entity.name.type',
        'entity.name.class',
        'entity.name.namespace',
        'entity.name.scope-resolution',
        'entity.other.inherited-class',
        'support.type',
        'support.class',
        'storage.type.class',
        'entity.name.type.interface',
        'entity.name.type.enum',
        'entity.name.type.struct',
        'entity.name.type.trait',
        'entity.name.type.module',
        'meta.type.annotation entity.name.type',
      ],
      settings: { foreground: a.amber },
    },
    {
      name: 'Primitive types',
      scope: [
        'support.type.primitive',
        'storage.type.primitive',
        'keyword.type',
        'entity.name.type.primitive',
      ],
      settings: { foreground: a.amber },
    },
    {
      name: 'Type parameters and generics',
      scope: ['meta.type.parameters entity.name.type', 'entity.name.type.parameter'],
      settings: { foreground: mix(a.amber, n.text, 0.25) },
    },
    {
      name: 'Object properties and keys',
      scope: [
        'variable.other.property',
        'variable.other.object.property',
        'support.type.property-name',
        'meta.object-literal.key',
        'variable.object.property',
        'entity.name.tag.yaml',
      ],
      settings: { foreground: a.sky },
    },
    {
      name: 'Object and namespace references',
      scope: ['variable.other.object', 'support.class.dom', 'support.variable.object'],
      settings: { foreground: n.text },
    },

    // -- Markup: HTML, JSX, XML ---------------------------------------------
    {
      name: 'HTML and JSX tags',
      scope: [
        'entity.name.tag',
        'entity.name.tag.html',
        'entity.name.tag.other',
        'meta.tag entity.name.tag',
        'support.class.component',
      ],
      settings: { foreground: a.rose },
    },
    {
      name: 'Component tags — capitalised JSX',
      scope: [
        'support.class.component.jsx',
        'support.class.component.tsx',
        'entity.name.tag.namespace',
      ],
      settings: { foreground: a.amber },
    },
    {
      name: 'Tag attributes',
      scope: [
        'entity.other.attribute-name',
        'entity.other.attribute-name.html',
        'meta.tag entity.other.attribute-name',
      ],
      settings: { foreground: a.sky },
    },
    {
      name: 'Tag punctuation',
      scope: [
        'punctuation.definition.tag',
        'punctuation.definition.tag.begin',
        'punctuation.definition.tag.end',
      ],
      settings: { foreground: mix(a.rose, n.muted, 0.45) },
    },

    // -- CSS ----------------------------------------------------------------
    {
      name: 'CSS selectors — classes',
      scope: [
        'entity.other.attribute-name.class',
        'entity.other.attribute-name.class.css',
        'entity.other.attribute-name.parent-selector',
      ],
      settings: { foreground: a.amber },
    },
    {
      name: 'CSS selectors — ids',
      scope: ['entity.other.attribute-name.id', 'entity.other.attribute-name.id.css'],
      settings: { foreground: a.apricot },
    },
    {
      name: 'CSS pseudo-classes and pseudo-elements',
      scope: [
        'entity.other.attribute-name.pseudo-class',
        'entity.other.attribute-name.pseudo-element',
        'meta.selector',
      ],
      settings: { foreground: a.orchid },
    },
    {
      name: 'CSS properties',
      scope: ['support.type.property-name.css', 'meta.property-name'],
      settings: { foreground: a.sky },
    },
    {
      name: 'CSS values and constants',
      scope: [
        'support.constant.property-value',
        'support.constant.font-name',
        'support.constant.color',
        'meta.property-value',
      ],
      settings: { foreground: a.teal },
    },
    {
      name: 'CSS at-rules',
      scope: ['keyword.control.at-rule', 'punctuation.definition.keyword.css'],
      settings: { foreground: a.lavender },
    },
    {
      name: 'CSS variables',
      scope: ['variable.css', 'variable.argument.css', 'support.type.custom-property'],
      settings: { foreground: a.orchid },
    },

    // -- Markdown -----------------------------------------------------------
    {
      name: 'Markdown headings',
      scope: ['markup.heading', 'entity.name.section.markdown'],
      settings: { foreground: a.teal, fontStyle: 'bold' },
    },
    {
      name: 'Markdown heading punctuation',
      scope: [
        'punctuation.definition.heading.markdown',
        'markup.heading.setext',
      ],
      settings: { foreground: mix(a.teal, n.muted, 0.4) },
    },
    { name: 'Markdown bold', scope: ['markup.bold'], settings: { foreground: a.apricot, fontStyle: 'bold' } },
    { name: 'Markdown italic', scope: ['markup.italic'], settings: { foreground: a.orchid, fontStyle: 'italic' } },
    {
      name: 'Markdown strikethrough',
      scope: ['markup.strikethrough'],
      settings: { foreground: n.muted, fontStyle: 'strikethrough' },
    },
    { name: 'Markdown links', scope: ['markup.underline.link', 'string.other.link.title'], settings: { foreground: a.sky } },
    { name: 'Markdown link text', scope: ['string.other.link.description'], settings: { foreground: a.lavender } },
    { name: 'Markdown code', scope: ['markup.inline.raw', 'markup.fenced_code', 'markup.raw'], settings: { foreground: a.green } },
    { name: 'Markdown quotes', scope: ['markup.quote'], settings: { foreground: n.subtle, fontStyle: 'italic' } },
    { name: 'Markdown lists', scope: ['markup.list', 'punctuation.definition.list.begin'], settings: { foreground: a.rose } },
    { name: 'Markdown separators', scope: ['meta.separator.markdown'], settings: { foreground: n.surface2 } },

    // -- Diff ---------------------------------------------------------------
    { name: 'Diff inserted', scope: ['markup.inserted', 'meta.diff.header.to-file'], settings: { foreground: a.green } },
    { name: 'Diff deleted', scope: ['markup.deleted', 'meta.diff.header.from-file'], settings: { foreground: st.red } },
    { name: 'Diff changed', scope: ['markup.changed'], settings: { foreground: a.amber } },
    { name: 'Diff range', scope: ['meta.diff.range', 'punctuation.definition.range.diff'], settings: { foreground: a.orchid } },

    // -- Config and data formats --------------------------------------------
    { name: 'JSON keys', scope: ['support.type.property-name.json'], settings: { foreground: a.sky } },
    {
      name: 'JSON nesting levels',
      scope: ['source.json meta.structure.dictionary.json support.type.property-name.json'],
      settings: { foreground: a.sky },
    },
    { name: 'YAML anchors and aliases', scope: ['entity.name.type.anchor.yaml', 'variable.other.alias.yaml'], settings: { foreground: a.orchid } },
    { name: 'INI and TOML sections', scope: ['entity.name.section.toml', 'entity.name.tag.ini'], settings: { foreground: a.amber } },
    { name: 'Environment keys', scope: ['keyword.other.definition.ini', 'variable.other.env'], settings: { foreground: a.sky } },

    // -- Shell --------------------------------------------------------------
    { name: 'Shell built-ins', scope: ['support.function.builtin.shell', 'entity.name.function.shell'], settings: { foreground: a.teal } },
    { name: 'Shell variables', scope: ['variable.other.normal.shell', 'punctuation.definition.variable.shell'], settings: { foreground: a.orchid } },
    { name: 'Shell options', scope: ['constant.other.option', 'variable.parameter.option'], settings: { foreground: a.apricot } },

    // -- Language specifics -------------------------------------------------
    { name: 'Python decorators and dunder', scope: ['support.function.magic.python', 'meta.function.decorator.python'], settings: { foreground: a.teal, fontStyle: 'italic' } },
    { name: 'Python self', scope: ['variable.parameter.function.language.special.self.python'], settings: { foreground: a.rose } },
    { name: 'Rust lifetimes and attributes', scope: ['storage.modifier.lifetime.rust', 'entity.name.lifetime.rust', 'meta.attribute.rust'], settings: { foreground: a.orchid } },
    { name: 'Go package and receiver', scope: ['entity.name.package.go', 'variable.other.receiver.go'], settings: { foreground: a.amber } },
    { name: 'C and C++ preprocessor', scope: ['keyword.control.directive', 'meta.preprocessor', 'punctuation.definition.directive'], settings: { foreground: a.orchid } },
    { name: 'SQL keywords', scope: ['keyword.other.DML', 'keyword.other.DDL'], settings: { foreground: a.lavender } },
    { name: 'GraphQL fields', scope: ['variable.graphql', 'meta.selection-set.graphql variable'], settings: { foreground: a.sky } },

    // -- States -------------------------------------------------------------
    { name: 'Invalid', scope: ['invalid', 'invalid.illegal'], settings: { foreground: st.red } },
    { name: 'Deprecated', scope: ['invalid.deprecated'], settings: { foreground: a.amber, fontStyle: 'strikethrough' } },
    { name: 'Broken and unimplemented', scope: ['invalid.broken', 'invalid.unimplemented'], settings: { foreground: st.red } },
  ];

  return {
    $schema: 'vscode://schemas/color-theme',
    name: variant.name,
    type: variant.type,
    semanticHighlighting: true,
    colors,
    semanticTokenColors,
    tokenColors,
  };
}

module.exports = { buildTheme };
